blueprint:
  name: Frigate Presence Detection Notifications Hardcoded
  source_url: "https://github.com/m2015agg/HA_Frigate_notifier/blob/main/blueprints/stable.yaml"
  description: >
    Spawn a single loop on each new Frigate event for watched cameras. With multiple devices
    Only notify when an object is detected in a zone and remains there for the specified presence time.
    This prevents notifications for quick pass-throughs and only alerts for sustained presence.
    # Version 1.5.1 (2024-05-09)
    # Updated: Added robust event validation
    # - Added event ID validation to ensure correct event processing
    # - Added camera name validation to prevent cross-camera confusion
    # - Improved notification conditions for better accuracy
    # Updated: Improved notification format
    # - Added platform-specific parameters for Android and iOS
    # - Updated action formatting with icons
    # - Fixed entity_id to use event ID
    # - Added proper sound configuration
    # Updated: Added cooldown period after notifications
    # - Configurable cooldown time (0-30 minutes)
    # - Automation ends after cooldown completes
    # - Improved end conditions for better control
    # Updated: Added robust event checks and detailed debug logging
    #
    # Note: The following features were tested but rolled back:
    # - Camera validation for snapshots (v1.2.0)
    #   * Added checks to ensure snapshot camera matches event camera
    #   * Prevented incorrect snapshots in notifications
    #   * Rolled back due to potential false negatives with cross-camera events
    #   * May be reimplemented with single-camera automations
    #
    # - Event path handling (v1.3.0)
    #   * Used Frigate's event path for notifications
    #   * Added fallback to event ID if path missing
    #   * Rolled back due to path inconsistencies between cameras
    #   * May be reimplemented with improved path validation
    #
    # - Modified notification behavior (v1.4.0)
    #   * Changed tap action to open thumbnail
    #   * Added additional quick actions
    #   * Rolled back due to notification reliability issues
    #   * May be reimplemented with single-camera focus
    #
    # Usage: This automation supports monitoring multiple cameras simultaneously.
    # Each camera's events are processed independently with their own cooldown periods.
    # The automation includes robust event matching to prevent cross-camera confusion.

  domain: automation
  input:
    camera:
      name: Camera
      description: Select a camera to monitor. Each camera should have its own automation instance.
      selector:
        entity:
          integration: frigate
          domain: camera
          multiple: false

    notify_group:
      name: Notify Service or Group
      description: Enter a `notify.` service (e.g., `notify.mobile_app_johns_iphone`, `notify.family_notifications`)
      default: "all_notify_devices"


    mqtt_review_topic:
      name: Review Topic
      default: frigate/reviews
      selector:
        text: {}

    mqtt_event_topic:
      name: Event Topic
      default: frigate/events
      selector:
        text: {}

    base_url:
      name: Home Assistant URL
      default: "https://nipu0uvuj0g8ngrg0sv9ekt1mihje4uo.ui.nabu.casa"
      selector:
        text: {}

    timeout:
      name: Update Timeout (minutes)
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

    cooldown:
      name: Cooldown Period (minutes)
      description: Time to wait after sending a notification before ending the automation
      default: 1
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: minutes

    enable_homekit:
      name: Enable HomeKit Alerts
      default: true
      selector:
        boolean: {}

    critical_alert:
      name: Enable Critical Alerts
      default: false
      selector:
        boolean: {}

    automation_mode:
      name: Automation Mode
      description: Choose how the automation handles multiple events
      default: parallel
      selector:
        select:
          options:
            - parallel
            - single
            - queued
          translation_key: automation_mode

# Run automation in selected mode
mode: !input automation_mode

# Trigger on MQTT updates from Frigate
# This trigger listens to frigate/reviews for new events
trigger:
  - platform: mqtt
    topic: !input mqtt_review_topic
    value_template: >
      {{ trigger.payload_json.type == 'new' and trigger.payload_json.after.camera == camera }}

# Variables used in the automation
variables:
  # Extract data from the MQTT payload frigate/reviews
  review_payload: "{{ trigger.payload_json }}"
  review_full_event_id: "{{ review_payload.after.id }}"
  review_camera_id: "{{ review_payload.after.camera }}"
  detection_id: "{{ review_payload.after.data.detections[0] }}"
  automation_name: "{{ this.entity_id }}"

  # Get input variables
  camera: !input camera
  notify_group: !input notify_group
  base_url: !input base_url
  timeout: !input timeout
  cooldown: !input cooldown
  enable_homekit: !input enable_homekit
  critical_alert: !input critical_alert
  mqtt_event_topic: !input mqtt_event_topic
  initial_notification_sent: false
  notification_time: null



action:
  - service: logbook.log
    data:
      name: "Frigate Debug - Initial Review Event"
      message: >
        Review Event: {{ review_full_event_id }}
        Camera: {{ review_camera_id }}
        Watched Cameras: {{ camera }}
        Multi-Camera Mode: Enabled

  - repeat:
      sequence:

        # 1) Log that we're waiting for the matching event
        - service: logbook.log
          data:
            name: "Frigate Debug - Waiting for Event"
            message: >
              Waiting for event ID: {{ review_full_event_id }}
              Review Camera: {{ review_camera_id }}
              On topic: {{ mqtt_event_topic }}
              Review Payload: {{ review_payload | to_json }}

        # 2) Block until we see the frigate/events message with the same ID
        - wait_for_trigger:
            - platform: mqtt
              topic: "{{ mqtt_event_topic }}"
              value_template: >-
                {{ wait.trigger.payload_json.after.id == detection_id }}
          timeout:
            minutes: "{{ timeout }}"
          continue_on_timeout: false

        # 3) Now pull the real event fields into local vars
        - variables:
            e: "{{ wait.trigger.payload_json.after }}"
            has_pending: "{{ e.pending_loitering | default(false) }}"
            has_zones: "{{ (e.entered_zones | default([])) | length > 0 }}"
            has_clip: "{{ e.has_clip | default(false) }}"
            has_snapshot: "{{ e.has_snapshot | default(false) }}"
            is_active: "{{ e.active | default(false) }}"
            has_severity: "{{ e.max_severity == 'alert' }}"
            should_notify: >-
              {{ (not initial_notification_sent)
                  and has_severity
                  and has_clip
                  and has_snapshot
                  and has_pending 
                  and has_zones
                  and e.camera == trigger.payload_json.after.camera }}

        # 4) Log what we've got
        - service: logbook.log
          data:
            name: "Frigate Debug - Event Received"
            message: >
              Review Event: {{ review_full_event_id }}
              Review Camera: {{ review_camera_id }}
              Event ID: {{ e.id }}
              Event Camera: {{ e.camera }}
              ID Match: {{ e.id == review_full_event_id }}
              Camera Match: {{ e.camera == review_camera_id }}
              Event Payload: {{ wait.trigger.payload_json | to_json }}
              Pending Loitering: {{ has_pending }}
              Has Clip: {{ has_clip }}
              Has Snapshot: {{ has_snapshot }}
              Severity OK: {{ has_severity }}
              Should Notify: {{ should_notify }}
              Validation:
              - Event ID Match: {{ e.id == review_full_event_id }}
              - Camera Match: {{ e.camera == review_camera_id }}

        # Check if we should send notification
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ should_notify }}"
              sequence:
                - service: logbook.log
                  data:
                    name: "Frigate Debug - Condition Check"
                    message: >
                      Event {{ review_full_event_id }} ({{ review_camera_id }})
                      Object: {{ e.label }} ({{ e.sub_label }})
                      Conditions:
                      - Initial notification not sent: {{ not initial_notification_sent }}
                      - Has severity: {{ has_severity }}
                      - Has pending loitering: {{ has_pending }}
                      - Has clip: {{ has_clip }}
                      - Has snapshot: {{ has_snapshot }}
                      - Is active: {{ is_active }}
                      Final decision: {{ should_notify }}

                - action: "notify.{{ notify_group }}"
                  data:
                    title: "Frigate Detection"
                    message: >-
                      A {{ e.label | title }} was detected on {{ e.camera }}.
                    data:
                      tag: "{{ e.id }}_{{ now().timestamp() | int }}"
                      group: "frigate"
                      color: "red"
                      # Android Specific
                      subject: "Frigate Detection"
                      image: "{{ base_url }}/api/frigate/notifications/{{ e.id }}/snapshot.jpg"
                      video: "{{ base_url }}/api/frigate/notifications/{{ e.id }}/clip.mp4"
                      clickAction: "{{ base_url }}/api/frigate/notifications/{{ e.id }}/snapshot.jpg"
                      ttl: 0
                      priority: high
                      notification_icon: "mdi:cctv"
                      sticky: false
                      channel: "{{ 'alarm_stream' if critical_alert else 'default' }}"
                      # iOS Specific
                      url: "{{ base_url }}/api/frigate/notifications/{{ e.id }}/clip.mp4"
                      attachment:
                        url: "{{ base_url }}/api/frigate/notifications/{{ e.id }}/snapshot.jpg"
                        content-type: "jpeg"
                      push:
                        sound:
                          name: "default"
                          volume: 1
                          critical: "{{ critical_alert }}"
                      entity_id: "camera.{{ e.camera | replace('-', '_') | lower }}"
                      # Actions
                      actions:
                        - action: URI
                          title: "Open Frigate Dashboard"
                          uri: "{{ base_url }}/ccab4aaf_frigate-fa/dashboard"
                          icon: "mdi:view-dashboard"
                        - action: URI
                          title: "View Clip"
                          uri: "{{ base_url }}/api/frigate/notifications/{{ e.id }}/master.m3u8"
                          icon: "mdi:video"
                        - action: "message_mute_{{ automation_name.split('.')[-1] }}"
                          title: "Mute 30 min"
                          icon: "mdi:volume-off"
                          destructive: true

                - variables:
                    initial_notification_sent: true
                    notification_time: "{{ now() }}"

                - choose:
                    - conditions: "{{ enable_homekit }}"
                      sequence:
                        - service: input_boolean.turn_on
                          target:
                            entity_id: >
                              input_boolean.frigate_{{ review_camera_id|lower }}_alert
                        - delay: 5
                        - service: input_boolean.turn_off
                          target:
                            entity_id: >
                              input_boolean.frigate_{{ review_camera_id|lower }}_alert

      until: >-
        {% if trigger is none %}
          true
        {% elif initial_notification_sent and notification_time %}
          {% set elapsed = (now() - notification_time).total_seconds() %}
          {% set cooldown_seconds = cooldown * 60 %}
          {% set should_end = elapsed > cooldown_seconds %}
          {{ should_end }}
        {% else %}
          false
        {% endif %}

  - service: logbook.log
    data:
      name: "Frigate Debug - Cooldown Status"
      message: >
        Event: {{ review_full_event_id }}
        Camera: {{ review_camera_id }}
        Notification Time: {{ notification_time }}
        Elapsed Seconds: {{ (now() - notification_time).total_seconds() if notification_time else 0 }}
        Cooldown Seconds: {{ cooldown * 60 }}
        Should End: {{ (now() - notification_time).total_seconds() > (cooldown * 60) if notification_time else false }}






  
